version: '3.4'
services:
  redis:
    image: redis:alpine
    restart: always
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata/
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    depends_on:
      - redis
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - redis
  nginx:
    image: nginx:1.19.2-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    restart: always
    depends_on:
      - app
    ports:
      - 80:80
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 16686:16686
    depends_on:
      - nginx
    restart: always

volumes:
  pgdata:
    external: true
    name: ${POSTGRES_VOLUME_NAME}