BASE_URL = "/user"
"""Базовый URL."""

REGISTER = "/register"
"""API регистрации."""
LOGIN = "/login"
"""API логина."""
LOGIN_HISTORY = "/login_history"
"""API истории входов в аккаунт."""
UPDATE = "/update"
"""API изменения данных."""
REFRESH_TOKEN = "/refresh_token"
"""API обновления токена доступа."""
LOGOUT = "/logout"
"""API выхода из аккаунта."""
